# Generated by Django 4.2.7 on 2023-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('medical_history', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
