# Generated by Django 4.2.7 on 2023-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Visit date')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('diagnosis', models.CharField(max_length=100)),
                ('treatment', models.TextField(max_length=250)),
                ('again', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
    ]
