# Generated by Django 4.2.7 on 2023-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_visits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='again',
            new_name='options',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
    ]
